### ISSUE TITLE
opencv not compatible

### ISSUE THREAD

**Issue by jrrk2** [msproul/AlpacaPi#1]
Thanks for making this program available.

I am trying to run AlpacaPi on an unstable version of Debian. It seems like my version of opencv is too new and provides opencv4/opencv2/highgui.hpp whereas you require opencv/highgui.h.

Is there a mention of the supported versions of external libraries anywhere ?

**Comment by msproul** [comment]
The current version of AlpacaPI requires openCV version 3.3.1 or earlier.
This is because I started using openCV 10 years ago when the C function calls were the more common interface.  3.3.1 was the last version that supported "C".

I am currently working VERY hard at updating to the openCV C++ interface. I am about 80% complete

There are several options currently available
You can make a driver that does not use openCV
    make noopencv  

Skytravel can be compiled with the new C++ interface
     make noopencv

**Comment by msproul** [comment]
The planetarium program, SkyTravel is now fully working with openCV4,  the camera drivers will work WITHOUT openCV but the openCV part is not finished.  It is real close.

**Comment by msproul** [comment]
Camera driver is mostly switched over to openCV C++ calls now.  It is enough so all of the standard functionality is complete.  Not ready to close the issue yet because it is not fully tested.

**Comment by msproul** [comment]
all of the components of AlpacaPi are now working on both Linux and RaspberryPi with version 4 of openCV only.
This issue is now closed. 
Thanks for bringing it up. It was a lot of work but worth it in the end.
